### ISSUE TITLE
Uncaught TypeError: _blockstack.PrivateKeychain is not a constructor on Account Creation

### ISSUE THREAD

**Issue by Omeryl** [blockstack/blockstack-portal#390] opened 2017-04-04 23:39 UTC
Creating an account, from scratch:

```
Uncaught TypeError: _blockstack.PrivateKeychain is not a constructor
    at http://localhost:8888/js/main.js:7425:25
    at http://localhost:8888/js/main.js:107360:18
    at Object.initializeWallet (http://localhost:8888/js/main.js:107439:12)
    at WelcomeModal.createAccount (http://localhost:8888/js/main.js:2429:20)
    at Object.invokeGuardedCallback (http://localhost:8888/js/main.js:86486:5)
    at executeDispatch (http://localhost:8888/js/main.js:80553:21)
    at Object.executeDispatchesInOrder (http://localhost:8888/js/main.js:80573:7)
    at executeDispatchesAndRelease (http://localhost:8888/js/main.js:79978:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8888/js/main.js:79989:10)
    at Array.forEach (native)
```

**Comment by larrysalibra** [comment] 2017-04-17 17:58
Thanks for reporting this @Omeryl !

This should be fixed. (It's a duplicate of #392)

**Closed by larrysalibra** 2017-04-17 17:58 UTC
Labels: bug

**Comment by Omeryl** [comment] 2017-04-17 21:05
@larrysalibra I think you mean the other way around ;). I believe I was the slack user too, I had reported in both mediums :p.

**Comment by larrysalibra** [comment] 2017-04-17 21:07
@Omeryl Definitely! You were the slack user. Thank you again!
